### ISSUE TITLE
Feedback concept 

### ISSUE THREAD

**Issue by NoorPoppe** [NoorPoppe/opdracht2_maak_het_persoonlijk#1]

**Comment by benoitboucart** [comment]
Leuk concept!

Denk wel nog na hoe je het allemaal zal visualiseren en hoe de gebruiker de kat kan personaliseren (misschien meer dan enkel de kleur?). Eventueel kan de gebruiker een foto van zijn eigen kat uploaden? Wat zal je tonen op de pagina met de gepersonaliseerde kat? 

Leuk ook dat je een galerij zal voorzien. Misschien kan je er ook een community aspect aan koppelen.

Vergeet ook niet na te denken over de nieuwe technologie / tool / ... die je zal implementeren in je project (zie briefing).
